# MarketForge
# Copyright (c) 2026 REICHHART Damien
#
# Licensed under the MIT License. See the LICENSE file in the project
# root for full license information.

"""
End-to-end stylized-facts integration tests.

Verifies that data generated by the full pipeline (config → OHLCVBuilder →
validate_ohlcv) satisfies the four core stylized facts across all supported
market types and multiple seeds.
"""

import numpy as np
import pytest

from marketforge.configs.loader import load_market_config, market_config_to_generator_config
from marketforge.generators.ohlcv import OHLCVBuilder
from marketforge.utils.random import RandomState
from marketforge.validation.report import validate_ohlcv
from marketforge.config.settings import MarketType

_TEN_DAYS = 10 * 86400


@pytest.mark.parametrize("seed", [123, 2024])
@pytest.mark.parametrize("market", ["crypto", "stocks", "forex"])
def test_generated_data_matches_stylized_facts(market, seed):
    mc = load_market_config(market)
    syms = mc.symbols[:3]
    cfg = market_config_to_generator_config(
        mc, start_timestamp=1704067200, end_timestamp=1704067200 + _TEN_DAYS,
        seed=seed, batch_symbols=syms,
    )
    builder = OHLCVBuilder(cfg)
    data = builder.build(RandomState(seed))

    d = data[syms[0]]
    report = validate_ohlcv(d.open, d.high, d.low, d.close, MarketType(market))
    assert report.get("excess_kurtosis").passed, report.summary()
    assert report.get("vol_clustering").passed, report.summary()
    assert report.get("leverage").passed, report.summary()
    assert report.get("range_efficiency").passed, report.summary()
