# MarketForge
# Copyright (C) 2026 REICHHART Damien
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
End-to-end stylized-facts integration tests.

Verifies that data generated by the full pipeline (config → OHLCVBuilder →
validate_ohlcv) satisfies the four core stylized facts across all supported
market types and multiple seeds.
"""

import numpy as np
import pytest

from marketforge.configs.loader import load_market_config, market_config_to_generator_config
from marketforge.generators.ohlcv import OHLCVBuilder
from marketforge.utils.random import RandomState
from marketforge.validation.report import validate_ohlcv
from marketforge.config.settings import MarketType

_TEN_DAYS = 10 * 86400


@pytest.mark.parametrize("seed", [123, 2024])
@pytest.mark.parametrize("market", ["crypto", "stocks", "forex"])
def test_generated_data_matches_stylized_facts(market, seed):
    mc = load_market_config(market)
    syms = mc.symbols[:3]
    cfg = market_config_to_generator_config(
        mc, start_timestamp=1704067200, end_timestamp=1704067200 + _TEN_DAYS,
        seed=seed, batch_symbols=syms,
    )
    builder = OHLCVBuilder(cfg)
    data = builder.build(RandomState(seed))

    d = data[syms[0]]
    report = validate_ohlcv(d.open, d.high, d.low, d.close, MarketType(market))
    assert report.get("excess_kurtosis").passed, report.summary()
    assert report.get("vol_clustering").passed, report.summary()
    assert report.get("leverage").passed, report.summary()
    assert report.get("range_efficiency").passed, report.summary()
